# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT wagae.wsgi

beta_settings:
    cloud_sql_instances: <INSTANCE CONNECTION NAME>

runtime_config:
  python_version: 2
# [END runtime]

